#!/bin/bash
export SECRET_KEY='ef3f32aab117166afda5b61a27af21c7'
export SQLALCHEMY_DATABASE_URI='sqlite:///site.db'
#export MAIL_SERVER='smtp.gmail.com'
#export MAIL_PORT='587'
#export MAIL_USE_TLS='True'
#export MAIL_USE_SSL='False'
#export MAIL_MAX_EMAILS='None'
export SQLALCHEMY_TRACK_MODIFICATIONS='True'
#export MAIL_USERNAME='krzyczyrazdwatrzy@gmail.com'
#export MAIL_DEFAULT_SENDER='krzyczyrazdwatrzy@gmail.com'